/**
 * 카탈로그 단일 원본.
 *
 * - Supabase 시드 SQL 생성(scripts/gen-seed.ts)의 입력이자,
 * - Supabase 연결이 없을 때 앱이 그대로 쓰는 폴백 데이터다.
 *
 * 이미지는 전부 실제로 열어보고 "무슨 신발인지" 확인한 것만 넣었다.
 * 브랜드 로고가 사진에 보이는 경우 그 브랜드로만 배정했다.
 */

import type { CategoryId, MoodId, ShoeType } from "./taxonomy";

export type SeedBrand = {
  slug: string;
  name: string;
  nameKo: string;
  category: CategoryId;
  country: string;
  sortOrder: number;
};

export type SeedProduct = {
  slug: string;
  name: string;
  nameKo: string;
  brandSlug: string;
  category: CategoryId;
  shoeType: ShoeType;
  price: number;
  compareAtPrice?: number;
  colorway: string;
  materials: string;
  description: string;
  story: string;
  /** images.unsplash.com/photo-{imageId} */
  imageId: string;
  imageAlt: string;
  sizes: number[];
  moods: MoodId[];
  isNew?: boolean;
  isBestseller?: boolean;
  stock: number;
};

export const SNEAKER_SIZES = [230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285];
export const HEEL_SIZES = [225, 230, 235, 240, 245, 250, 255];
export const DRESS_SIZES = [240, 245, 250, 255, 260, 265, 270, 275, 280];
export const BOOT_SIZES = [230, 235, 240, 245, 250, 255, 260, 265, 270, 275];

export function imageUrl(imageId: string, w = 900, h = 1125): string {
  return `https://images.unsplash.com/photo-${imageId}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;
}

/** 가상 실착 스튜디오 배경으로 쓰는 전신 모델컷. 전부 발까지 나온 사진만 검증해서 골랐다. */
export type ModelShot = {
  id: string;
  label: string;
  imageId: string;
  /** 발이 대략 어디쯤인지 (0~1 비율) — 캔버스에서 신발 초기 위치를 잡는 데 쓴다 */
  footHint: { x: number; y: number; scale: number };
};

export const MODEL_SHOTS: ModelShot[] = [
  {
    id: "street-m",
    label: "스트리트 · 남성",
    imageId: "1516826957135-700dedea698c",
    footHint: { x: 0.44, y: 0.9, scale: 0.1 },
  },
  {
    id: "casual-w",
    label: "캐주얼 · 여성",
    imageId: "1515886657613-9f3515b0c78f",
    footHint: { x: 0.5, y: 0.88, scale: 0.095 },
  },
  {
    id: "daily-w",
    label: "데일리 · 여성",
    imageId: "1509087859087-a384654eca4d",
    footHint: { x: 0.5, y: 0.9, scale: 0.1 },
  },
  {
    id: "city-coat",
    label: "시티 코트",
    imageId: "1539109136881-3be0616acf4b",
    footHint: { x: 0.48, y: 0.9, scale: 0.09 },
  },
  {
    id: "dressy-w",
    label: "드레시 · 하객",
    imageId: "1485968579580-b6d095142e6e",
    footHint: { x: 0.5, y: 0.91, scale: 0.11 },
  },
  {
    id: "office-m",
    label: "오피스 · 남성",
    imageId: "1552374196-1ab2a1c593e8",
    footHint: { x: 0.45, y: 0.87, scale: 0.09 },
  },
  {
    id: "resort-w",
    label: "리조트 · 여성",
    imageId: "1614251055880-ee96e4803393",
    footHint: { x: 0.5, y: 0.9, scale: 0.095 },
  },
];

export const BRANDS: SeedBrand[] = [
  // 스포츠
  { slug: "nike", name: "Nike", nameKo: "나이키", category: "sports", country: "미국", sortOrder: 1 },
  { slug: "jordan", name: "Jordan", nameKo: "조던", category: "sports", country: "미국", sortOrder: 2 },
  { slug: "adidas", name: "adidas", nameKo: "아디다스", category: "sports", country: "독일", sortOrder: 3 },
  { slug: "new-balance", name: "New Balance", nameKo: "뉴발란스", category: "sports", country: "미국", sortOrder: 4 },
  { slug: "puma", name: "PUMA", nameKo: "푸마", category: "sports", country: "독일", sortOrder: 5 },
  { slug: "vans", name: "Vans", nameKo: "반스", category: "sports", country: "미국", sortOrder: 6 },
  { slug: "converse", name: "Converse", nameKo: "컨버스", category: "sports", country: "미국", sortOrder: 7 },
  // 명품
  { slug: "chanel", name: "CHANEL", nameKo: "샤넬", category: "luxury", country: "프랑스", sortOrder: 10 },
  { slug: "prada", name: "PRADA", nameKo: "프라다", category: "luxury", country: "이탈리아", sortOrder: 11 },
  { slug: "gucci", name: "GUCCI", nameKo: "구찌", category: "luxury", country: "이탈리아", sortOrder: 12 },
  { slug: "saint-laurent", name: "SAINT LAURENT", nameKo: "생로랑", category: "luxury", country: "프랑스", sortOrder: 13 },
  { slug: "bottega-veneta", name: "BOTTEGA VENETA", nameKo: "보테가 베네타", category: "luxury", country: "이탈리아", sortOrder: 14 },
  { slug: "balenciaga", name: "BALENCIAGA", nameKo: "발렌시아가", category: "luxury", country: "프랑스", sortOrder: 15 },
  { slug: "celine", name: "CELINE", nameKo: "셀린", category: "luxury", country: "프랑스", sortOrder: 16 },
  { slug: "jimmy-choo", name: "JIMMY CHOO", nameKo: "지미 추", category: "luxury", country: "영국", sortOrder: 17 },
  { slug: "berluti", name: "BERLUTI", nameKo: "벨루티", category: "luxury", country: "프랑스", sortOrder: 18 },
  // 컨템포러리
  { slug: "veja", name: "VEJA", nameKo: "베자", category: "contemporary", country: "프랑스", sortOrder: 20 },
  { slug: "churchs", name: "Church's", nameKo: "처치스", category: "contemporary", country: "영국", sortOrder: 21 },
  { slug: "paul-smith", name: "Paul Smith", nameKo: "폴 스미스", category: "contemporary", country: "영국", sortOrder: 22 },
  { slug: "grenson", name: "Grenson", nameKo: "그렌슨", category: "contemporary", country: "영국", sortOrder: 23 },
];

export const PRODUCTS: SeedProduct[] = [
  // ─────────────────────────── 스포츠 브랜드 ───────────────────────────
  {
    slug: "nike-free-run-crimson",
    name: "Free Run Flyknit",
    nameKo: "프리 런 플라이니트 크림슨",
    brandSlug: "nike",
    category: "sports",
    shoeType: "running",
    price: 129000,
    compareAtPrice: 159000,
    colorway: "크림슨 레드 / 화이트",
    materials: "플라이니트 어퍼, 폼 미드솔",
    description: "맨발에 가까운 착화감을 목표로 만든 경량 러닝화입니다. 발등 전체를 감싸는 플라이니트가 발 모양대로 늘어나 조임 없이 고정됩니다.",
    story: "짧은 거리를 빠르게 달리거나 러닝 후 회복 조깅을 할 때 진가를 발휘합니다. 접어서 가방에 넣을 수 있을 만큼 유연해 출장용으로도 좋습니다.",
    imageId: "1542291026-7eec264c27ff",
    imageAlt: "크림슨 레드 플라이니트 나이키 러닝화 측면",
    sizes: SNEAKER_SIZES,
    moods: ["sporty", "walk"],
    isBestseller: true,
    stock: 24,
  },
  {
    slug: "nike-air-force-1-tan",
    name: "Air Force 1 07 LV8",
    nameKo: "에어포스 1 LV8 탄",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 139000,
    colorway: "휘트 탄 / 검",
    materials: "스웨이드·누벅 어퍼, 에어솔 유닛",
    description: "1982년 농구화로 태어난 에어포스 1의 스웨이드 버전입니다. 가을·겨울 옷차림에 잘 붙는 따뜻한 탄 컬러로 나왔습니다.",
    story: "흰색 에어포스가 이미 있다면 다음은 이 색입니다. 데님·코듀로이·베이지 치노 어디에 신어도 톤이 맞습니다.",
    imageId: "1549298916-b41d501d3772",
    imageAlt: "휘트 탄 스웨이드 나이키 에어포스 1 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "date", "walk"],
    stock: 30,
  },
  {
    slug: "nike-af1-shadow-pastel",
    name: "Air Force 1 Shadow",
    nameKo: "에어포스 1 섀도우 파스텔",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 159000,
    colorway: "파스텔 멀티 / 화이트",
    materials: "레더 어퍼, 더블 스우시",
    description: "스우시와 미드솔을 겹쳐 쌓아 볼륨을 키운 여성용 에어포스입니다. 파스텔 톤이 층층이 들어가 각도마다 색이 다르게 보입니다.",
    story: "굽이 두꺼워 키가 2cm 정도 커 보입니다. 원피스나 와이드 팬츠처럼 실루엣이 큰 옷과 균형이 잘 맞습니다.",
    imageId: "1595950653106-6c9ebd614d3a",
    imageAlt: "파스텔 컬러 나이키 에어포스 1 섀도우 스니커즈",
    sizes: [225, 230, 235, 240, 245, 250, 255, 260],
    moods: ["date", "campus", "walk"],
    isNew: true,
    stock: 18,
  },
  {
    slug: "nike-air-max-sunset",
    name: "Air Max SC",
    nameKo: "에어맥스 SC 선셋",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 119000,
    colorway: "화이트 / 선셋 오렌지",
    materials: "레더·메시 어퍼, 비저블 에어",
    description: "뒤꿈치의 에어 유닛이 밖에서 보이는 클래식한 구성입니다. 화이트 베이스에 오렌지 그라데이션이 들어가 가벼운 인상을 줍니다.",
    story: "에어맥스 계열 중 가격 부담이 가장 적은 축입니다. 첫 에어맥스로 고르기 좋습니다.",
    imageId: "1600185365483-26d7a4cc7519",
    imageAlt: "화이트와 선셋 오렌지 나이키 에어맥스 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["walk", "campus"],
    stock: 26,
  },
  {
    slug: "nike-superrep-volt",
    name: "SuperRep Go 3",
    nameKo: "슈퍼렙 고 3 볼트",
    brandSlug: "nike",
    category: "sports",
    shoeType: "running",
    price: 149000,
    colorway: "볼트 그린 / 블랙",
    materials: "통기성 메시, 와이드 아웃솔",
    description: "실내 트레이닝 전용으로 설계했습니다. 바닥이 넓고 평평해서 스쿼트나 런지처럼 좌우로 흔들리는 동작에서 발이 밀리지 않습니다.",
    story: "러닝화로 웨이트를 하면 뒤꿈치가 푹 꺼져 자세가 무너집니다. 헬스장에 다닌다면 이런 신발이 따로 하나 있어야 합니다.",
    imageId: "1606107557195-0e29a4b5b4aa",
    imageAlt: "볼트 그린 나이키 슈퍼렙 트레이닝화",
    sizes: SNEAKER_SIZES,
    moods: ["sporty"],
    isNew: true,
    stock: 20,
  },
  {
    slug: "nike-air-max-90",
    name: "Air Max 90",
    nameKo: "에어맥스 90",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 179000,
    colorway: "화이트 / 오렌지 / 로열 블루",
    materials: "레더·메시 패널, 비저블 에어",
    description: "1990년에 나온 원형을 거의 그대로 유지한 모델입니다. 패널마다 소재와 색을 나눠 쓴 구성이 지금 봐도 촌스럽지 않습니다.",
    story: "30년 넘게 팔리는 데는 이유가 있습니다. 유행을 타지 않아 오래 신을 수 있는 몇 안 되는 스니커입니다.",
    imageId: "1514989940723-e8e51635b782",
    imageAlt: "오렌지와 블루 배색의 나이키 에어맥스 90 착용 컷",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "walk"],
    isBestseller: true,
    stock: 22,
  },
  {
    slug: "nike-pegasus-shield",
    name: "Pegasus Shield",
    nameKo: "페가수스 쉴드 블랙",
    brandSlug: "nike",
    category: "sports",
    shoeType: "running",
    price: 159000,
    colorway: "블랙 / 다크 그레이",
    materials: "발수 코팅 어퍼, 리액트 폼",
    description: "비 오는 날 달리기 위한 러닝화입니다. 어퍼에 발수 처리를 하고 아웃솔 패턴을 젖은 노면에 맞춰 바꿨습니다.",
    story: "장마철에 러닝을 쉬지 않으려면 이 신발이 필요합니다. 다만 완전 방수는 아니라 폭우에는 물이 들어옵니다.",
    imageId: "1491553895911-0055eca6402d",
    imageAlt: "블랙 컬러 나이키 러닝화",
    sizes: SNEAKER_SIZES,
    moods: ["sporty", "walk"],
    stock: 16,
  },
  {
    slug: "jordan-1-high-royal",
    name: "Air Jordan 1 Retro High OG",
    nameKo: "에어 조던 1 레트로 하이 OG 로얄",
    brandSlug: "jordan",
    category: "sports",
    shoeType: "sneakers",
    price: 289000,
    colorway: "블랙 / 로열 블루",
    materials: "풀그레인 레더, 에어솔",
    description: "1985년 오리지널 배색을 되살린 모델입니다. 발목을 덮는 하이컷과 두툼한 가죽이 특유의 무게감을 만듭니다.",
    story: "농구화로 시작해 지금은 문화가 된 신발입니다. 처음엔 가죽이 뻣뻣하지만 2주쯤 지나면 발에 맞게 접힙니다.",
    imageId: "1603787081207-362bcef7c144",
    imageAlt: "블랙과 로열 블루 배색의 에어 조던 1 하이탑",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "date"],
    isBestseller: true,
    stock: 12,
  },
  {
    slug: "jordan-1-unc",
    name: "Air Jordan 1 Retro High University Blue",
    nameKo: "에어 조던 1 레트로 하이 UNC",
    brandSlug: "jordan",
    category: "sports",
    shoeType: "sneakers",
    price: 319000,
    colorway: "유니버시티 블루 / 화이트",
    materials: "레더 어퍼, 러버 아웃솔",
    description: "노스캐롤라이나 대학 팀 컬러에서 가져온 하늘색 배색입니다. 흰 바탕에 파랑이 크게 들어가 여름에 특히 잘 어울립니다.",
    story: "조던 1 배색 중에서도 인기가 높은 편이라 사이즈가 빨리 빠집니다.",
    imageId: "1588099768531-a72d4a198538",
    imageAlt: "유니버시티 블루 에어 조던 1 착용 컷",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "date"],
    stock: 9,
  },
  {
    slug: "jordan-1-bred",
    name: "Air Jordan 1 High OG Bred",
    nameKo: "에어 조던 1 하이 OG 브레드",
    brandSlug: "jordan",
    category: "sports",
    shoeType: "sneakers",
    price: 299000,
    colorway: "블랙 / 바시티 레드",
    materials: "풀그레인 레더",
    description: "검정과 빨강만 쓴 가장 상징적인 배색입니다. 리그가 착용을 금지했다는 일화로 더 유명해졌습니다.",
    story: "무채색 옷이 많은 옷장이라면 이 한 켤레가 포인트를 전부 담당합니다.",
    imageId: "1552346154-21d32810aba3",
    imageAlt: "블랙과 레드 배색 에어 조던 1 하이탑 한 켤레",
    sizes: SNEAKER_SIZES,
    moods: ["campus"],
    stock: 11,
  },
  {
    slug: "jordan-1-shattered-backboard",
    name: "Air Jordan 1 Shattered Backboard",
    nameKo: "에어 조던 1 슈터드 백보드",
    brandSlug: "jordan",
    category: "sports",
    shoeType: "sneakers",
    price: 349000,
    colorway: "블랙 / 스타피시 오렌지",
    materials: "레더 어퍼, 스웨이드 힐탭",
    description: "주황과 검정이 절반씩 나뉜 배색입니다. 1985년 이탈리아 시범경기에서 백보드를 깨뜨렸던 경기의 유니폼 색을 옮겨왔습니다.",
    story: "발목에 오렌지가 크게 들어가 크롭 팬츠나 롤업 데님처럼 발목이 보이는 바지와 함께 신으면 가장 예쁩니다.",
    imageId: "1556906781-9a412961c28c",
    imageAlt: "오렌지와 블랙 배색 에어 조던 1 착용 컷",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "sporty"],
    stock: 8,
  },
  {
    slug: "jordan-1-chicago",
    name: "Air Jordan 1 High OG Chicago",
    nameKo: "에어 조던 1 하이 OG 시카고",
    brandSlug: "jordan",
    category: "sports",
    shoeType: "sneakers",
    price: 399000,
    colorway: "화이트 / 바시티 레드 / 블랙",
    materials: "프리미엄 레더",
    description: "조던 1을 대표하는 배색입니다. 흰 가죽에 빨강과 검정을 나눠 넣은 구성으로, 모든 복각의 기준이 되는 모델입니다.",
    story: "스니커를 한 켤레만 소장한다면 많은 사람이 이걸 고릅니다. 흰 가죽은 생각보다 때가 잘 타니 방수 스프레이를 권합니다.",
    imageId: "1597045566677-8cf032ed6634",
    imageAlt: "화이트 레드 블랙 배색의 에어 조던 1 시카고",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "date"],
    isBestseller: true,
    stock: 6,
  },
  {
    slug: "nike-blazer-mid-77",
    name: "Blazer Mid 77 Vintage",
    nameKo: "블레이저 미드 77 빈티지",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 139000,
    colorway: "크림 / 오렌지",
    materials: "레더 어퍼, 빈티지 가공 미드솔",
    description: "1977년 농구화를 복각하면서 미드솔에 일부러 누런 빛을 넣었습니다. 새 신발인데도 오래 신은 것 같은 분위기가 납니다.",
    story: "조던 1보다 가볍고 발볼이 편합니다. 하이탑이 부담스러운 분께 권합니다.",
    imageId: "1584735175315-9d5df23860e6",
    imageAlt: "크림과 오렌지 배색의 나이키 블레이저 미드 하이탑",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "date"],
    stock: 19,
  },
  {
    slug: "nike-af1-mid-cream",
    name: "Air Force 1 Mid",
    nameKo: "에어포스 1 미드 크림",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 149000,
    colorway: "크림 / 새들 브라운",
    materials: "레더 어퍼, 스트랩 디테일",
    description: "발목 스트랩이 달린 미드컷입니다. 로우보다 발목을 잡아줘 착화감이 안정적입니다.",
    story: "스트랩은 풀어서 늘어뜨려도 되고 채워도 됩니다. 채우면 단정하고, 풀면 느슨한 인상이 납니다.",
    imageId: "1512374382149-233c42b6a83b",
    imageAlt: "크림 컬러 나이키 에어포스 1 미드",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "walk"],
    stock: 15,
  },
  {
    slug: "nike-air-max-pink-blast",
    name: "Air Max Pink Blast",
    nameKo: "에어맥스 핑크 블라스트",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 189000,
    colorway: "화이트 / 핑크 블라스트 / 퍼플",
    materials: "메시·레더 혼합, 풀렝스 에어",
    description: "흰 바탕에 형광에 가까운 핑크를 크게 넣었습니다. 뒤꿈치 에어 유닛까지 색이 이어져 옆에서 봤을 때 선이 살아납니다.",
    story: "무채색 위주 옷차림에 색 하나만 넣고 싶을 때 좋습니다.",
    imageId: "1511556532299-8f662fc26c06",
    imageAlt: "화이트와 핑크 배색의 나이키 에어맥스",
    sizes: [225, 230, 235, 240, 245, 250, 255, 260, 265],
    moods: ["date", "campus"],
    isNew: true,
    stock: 14,
  },
  {
    slug: "nike-kyrie-infinity",
    name: "Kyrie Infinity",
    nameKo: "카이리 인피니티",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 179000,
    colorway: "블랙 / 화이트",
    materials: "합성 어퍼, 멀티 트랙션 아웃솔",
    description: "방향 전환이 잦은 가드 포지션을 위해 만든 농구화입니다. 앞꿈치 아웃솔을 곡선으로 깎아 급정지와 회전이 부드럽습니다.",
    story: "실내 코트용입니다. 아스팔트에서 신으면 아웃솔이 금방 닳습니다.",
    imageId: "1605348532760-6753d2c43329",
    imageAlt: "블랙 컬러 나이키 카이리 농구화",
    sizes: SNEAKER_SIZES,
    moods: ["sporty"],
    stock: 13,
  },
  {
    slug: "nike-af1-white",
    name: "Air Force 1 07",
    nameKo: "에어포스 1 화이트",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 139000,
    colorway: "트리플 화이트",
    materials: "풀그레인 레더, 에어솔 유닛",
    description: "설명이 필요 없는 흰 스니커의 기준입니다. 전부 흰색이라 어떤 옷에도 붙고, 더러워지면 눈에 띄지만 닦기도 쉽습니다.",
    story: "슬랙스에 신으면 캐주얼한 오피스룩이 되고, 반바지에 신으면 여름 데일리가 됩니다. 한 켤레로 계절 전체를 버팁니다.",
    imageId: "1600269452121-4f2416e55c28",
    imageAlt: "올 화이트 나이키 에어포스 1 로우",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "office", "walk"],
    isBestseller: true,
    stock: 40,
  },
  {
    slug: "nike-af1-black",
    name: "Air Force 1 07 Black",
    nameKo: "에어포스 1 블랙",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 139000,
    colorway: "트리플 블랙",
    materials: "풀그레인 레더, 에어솔 유닛",
    description: "흰색만큼 팔리는 검정 버전입니다. 때가 덜 타서 비 오는 날이나 출퇴근용으로 실용적입니다.",
    story: "검정 슬랙스와 함께라면 가장 무난하게 정돈된 인상을 줍니다.",
    imageId: "1570464197285-9949814674a7",
    imageAlt: "올 블랙 나이키 에어포스 1 로우",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "office", "date"],
    stock: 35,
  },
  {
    slug: "nike-air-retro-teal",
    name: "Air Retro Runner",
    nameKo: "에어 레트로 러너 틸",
    brandSlug: "nike",
    category: "sports",
    shoeType: "running",
    price: 129000,
    colorway: "화이트 / 틸 / 오렌지",
    materials: "메시·스웨이드 혼합",
    description: "90년대 러닝화 실루엣을 그대로 가져온 복각 모델입니다. 굽이 낮고 발볼이 좁아 발이 작아 보입니다.",
    story: "요즘 두꺼운 밑창이 부담스럽다면 이런 납작한 레트로 러너가 대안입니다.",
    imageId: "1595341888016-a392ef81b7de",
    imageAlt: "화이트와 틸 배색의 레트로 러닝화",
    sizes: SNEAKER_SIZES,
    moods: ["walk", "travel", "campus"],
    stock: 17,
  },
  {
    slug: "nike-md-runner-olive",
    name: "MD Runner 2",
    nameKo: "MD 러너 2 올리브",
    brandSlug: "nike",
    category: "sports",
    shoeType: "sneakers",
    price: 89000,
    colorway: "올리브 / 검 솔",
    materials: "스웨이드 어퍼, 검 러버 아웃솔",
    description: "가볍고 굽이 낮은 데일리 스니커입니다. 올리브 스웨이드에 검 솔을 붙여 차분한 인상을 줍니다.",
    story: "10만원 아래에서 고를 수 있는 가장 무난한 선택입니다. 첫 스니커나 세컨 슈즈로 권합니다.",
    imageId: "1576672843344-f01907a9d40c",
    imageAlt: "올리브 스웨이드 나이키 MD 러너 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["walk", "campus"],
    stock: 28,
  },
  {
    slug: "adidas-prophere-teal",
    name: "Prophere",
    nameKo: "프로피어 틸",
    brandSlug: "adidas",
    category: "sports",
    shoeType: "sneakers",
    price: 139000,
    colorway: "틸 / 핑크",
    materials: "니트 어퍼, 대형 러버 아웃솔",
    description: "톱니처럼 깎은 아웃솔과 두꺼운 니트 어퍼가 특징입니다. 실루엣이 커서 발이 커 보입니다.",
    story: "조거 팬츠나 와이드 팬츠처럼 밑단이 넓은 바지와 비율이 맞습니다.",
    imageId: "1520256862855-398228c41684",
    imageAlt: "틸과 핑크 배색의 아디다스 프로피어 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["sporty", "campus"],
    stock: 12,
  },
  {
    slug: "nb-x90-pink",
    name: "X-90",
    nameKo: "X-90 핑크",
    brandSlug: "new-balance",
    category: "sports",
    shoeType: "sneakers",
    price: 139000,
    colorway: "핑크 / 그레이",
    materials: "스웨이드·메시 어퍼, ABZORB 쿠션",
    description: "90년대 뉴발란스 러닝화를 재해석한 모델입니다. 핑크와 그레이를 섞어 부드러운 인상을 만들었습니다.",
    story: "뉴발란스 특유의 넓은 발볼 덕분에 오래 걸어도 발이 아프지 않습니다.",
    imageId: "1551107696-a4b0c5a0d9a2",
    imageAlt: "핑크와 그레이 배색의 뉴발란스 스니커즈",
    sizes: [225, 230, 235, 240, 245, 250, 255, 260, 265],
    moods: ["date", "walk", "campus"],
    stock: 16,
  },
  {
    slug: "nb-247-olive",
    name: "247",
    nameKo: "247 올리브",
    brandSlug: "new-balance",
    category: "sports",
    shoeType: "sneakers",
    price: 119000,
    colorway: "올리브 / 화이트",
    materials: "니트 어퍼, REVlite 미드솔",
    description: "하루 24시간 7일 신는다는 뜻의 이름입니다. 양말처럼 발을 감싸는 니트 어퍼에 가벼운 미드솔을 붙였습니다.",
    story: "무게가 한 짝에 250g 남짓이라 여행용 캐리어에 넣기 좋습니다.",
    imageId: "1539185441755-769473a23570",
    imageAlt: "올리브 컬러 뉴발란스 247 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["walk", "travel", "campus"],
    stock: 21,
  },
  {
    slug: "nb-574-white",
    name: "574 Core",
    nameKo: "574 코어 화이트",
    brandSlug: "new-balance",
    category: "sports",
    shoeType: "sneakers",
    price: 109000,
    colorway: "화이트 / 오렌지",
    materials: "스웨이드·메시, ENCAP 미드솔",
    description: "뉴발란스에서 가장 많이 팔린 모델입니다. 굽이 적당히 있고 발볼이 넉넉해 누구에게나 무난합니다.",
    story: "사이즈를 고민한다면 574부터 신어보세요. 뉴발란스 사이즈 감을 잡는 기준이 됩니다.",
    imageId: "1465453869711-7e174808ace9",
    imageAlt: "화이트와 오렌지 배색의 뉴발란스 574",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "walk"],
    isBestseller: true,
    stock: 32,
  },
  {
    slug: "puma-court-white",
    name: "Court Classic",
    nameKo: "코트 클래식 화이트",
    brandSlug: "puma",
    category: "sports",
    shoeType: "sneakers",
    price: 99000,
    colorway: "화이트 / 블랙 폼스트라이프",
    materials: "레더 어퍼, 러버 컵솔",
    description: "테니스 코트화에서 온 단순한 흰 스니커입니다. 옆면에 검정 폼스트라이프만 들어가 군더더기가 없습니다.",
    story: "10만원 아래 흰 가죽 스니커 중에서 마감이 좋은 편입니다. 오피스 캐주얼에도 무리 없습니다.",
    imageId: "1608231387042-66d1773070a5",
    imageAlt: "화이트 레더 푸마 코트 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["office", "campus", "walk"],
    stock: 25,
  },
  {
    slug: "puma-rsx-sand",
    name: "RS-X Reinvention",
    nameKo: "RS-X 리인벤션 샌드",
    brandSlug: "puma",
    category: "sports",
    shoeType: "sneakers",
    price: 149000,
    colorway: "샌드 / 코랄",
    materials: "메시·스웨이드 레이어드 어퍼",
    description: "80년대 러닝 시스템을 과장해 되살린 청키 스니커입니다. 여러 겹의 패널이 층을 이뤄 볼륨이 큽니다.",
    story: "샌드와 코랄이라 청키한데도 부담스럽지 않습니다. 청키 스니커 입문용으로 좋습니다.",
    imageId: "1608667508764-33cf0726b13a",
    imageAlt: "샌드와 코랄 배색의 푸마 RS-X 청키 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "date"],
    isNew: true,
    stock: 18,
  },
  {
    slug: "vans-old-skool-burgundy",
    name: "Old Skool",
    nameKo: "올드스쿨 버건디",
    brandSlug: "vans",
    category: "sports",
    shoeType: "sneakers",
    price: 79000,
    colorway: "버건디 / 화이트",
    materials: "스웨이드·캔버스, 와플 아웃솔",
    description: "옆면 사이드스트라이프가 처음 들어간 반스의 대표 모델입니다. 버건디는 검정보다 부드럽고 흰색보다 관리가 쉽습니다.",
    story: "와플 아웃솔은 접지력이 좋아 스케이트보드용으로 만들어졌습니다. 그만큼 바닥이 잘 미끄러지지 않습니다.",
    imageId: "1525966222134-fcfa99b8ae77",
    imageAlt: "버건디 컬러 반스 올드스쿨 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "walk"],
    stock: 30,
  },
  {
    slug: "converse-chuck70-green",
    name: "Chuck 70 Hi",
    nameKo: "척 70 하이탑 그린",
    brandSlug: "converse",
    category: "sports",
    shoeType: "sneakers",
    price: 99000,
    colorway: "포레스트 그린 / 아이보리",
    materials: "헤비 캔버스, 이집션 코튼 안감",
    description: "1970년대 사양으로 만든 복각판입니다. 일반 척보다 캔버스가 두껍고 미드솔이 높아 착화감이 단단합니다.",
    story: "일반 올스타를 신어봤다면 차이가 바로 느껴집니다. 가격이 조금 높지만 형태가 훨씬 오래 유지됩니다.",
    imageId: "1463100099107-aa0980c362e6",
    imageAlt: "포레스트 그린 컨버스 척 70 하이탑 착용 컷",
    sizes: SNEAKER_SIZES,
    moods: ["campus", "date"],
    stock: 22,
  },
  {
    slug: "converse-chuck-red",
    name: "Chuck Taylor All Star Hi",
    nameKo: "척 테일러 올스타 하이 레드",
    brandSlug: "converse",
    category: "sports",
    shoeType: "sneakers",
    price: 89000,
    colorway: "레드 / 화이트",
    materials: "캔버스 어퍼, 러버 아웃솔",
    description: "100년 넘게 형태가 거의 바뀌지 않은 신발입니다. 빨강은 척 테일러에서 가장 오래된 색 중 하나입니다.",
    story: "캔버스라 처음엔 뻣뻣하지만 몇 번 신으면 발 모양대로 접힙니다. 세탁기에 돌려도 견딥니다.",
    imageId: "1607522370275-f14206abe5d3",
    imageAlt: "레드 컨버스 척 테일러 올스타 하이탑",
    sizes: SNEAKER_SIZES,
    moods: ["campus"],
    stock: 26,
  },

  // ──────────────────────────── 명품 브랜드 ────────────────────────────
  {
    slug: "chanel-slingback-sandal",
    name: "Slingback Strap Sandal",
    nameKo: "슬링백 스트랩 샌들힐",
    brandSlug: "chanel",
    category: "luxury",
    shoeType: "heels",
    price: 1890000,
    colorway: "블랙 / 누드",
    materials: "카프스킨, 레더 아웃솔",
    description: "발등을 가로지르는 가는 스트랩과 뒤꿈치를 감는 슬링백을 함께 쓴 구조입니다. 발이 드러나는 면적이 넓어 다리가 길어 보입니다.",
    story: "하객룩에서 가장 많이 선택되는 형태입니다. 슬링백은 뒤가 막힌 펌프스보다 시원하고 벗겨질 걱정도 적습니다.",
    imageId: "1598554747436-c9293d6a588f",
    imageAlt: "블랙 스트랩 슬링백 힐을 착용한 모습",
    sizes: HEEL_SIZES,
    moods: ["wedding", "party", "date"],
    isBestseller: true,
    stock: 5,
  },
  {
    slug: "prada-stiletto-pump",
    name: "Leather Stiletto Pump",
    nameKo: "블랙 레더 스틸레토 펌프스",
    brandSlug: "prada",
    category: "luxury",
    shoeType: "heels",
    price: 1290000,
    colorway: "블랙",
    materials: "브러쉬드 카프 레더",
    description: "앞코를 뾰족하게 다듬고 굽을 가늘게 세운 정통 스틸레토입니다. 장식 없이 선만으로 완성한 형태입니다.",
    story: "9cm 굽이라 오래 서 있기는 어렵습니다. 앉아 있는 시간이 긴 자리에 신으세요. 앞꿈치 쿠션을 넣으면 체감이 크게 달라집니다.",
    imageId: "1596703263926-eb0762ee17e4",
    imageAlt: "블랙 레더 스틸레토 펌프스",
    sizes: HEEL_SIZES,
    moods: ["office", "party", "wedding"],
    stock: 6,
  },
  {
    slug: "gucci-floral-pump",
    name: "Floral Print Pump",
    nameKo: "플로럴 프린트 펌프스",
    brandSlug: "gucci",
    category: "luxury",
    shoeType: "heels",
    price: 1480000,
    colorway: "멀티 플로럴",
    materials: "실크 새틴, 레더 라이닝",
    description: "실크 위에 꽃무늬를 프린트한 펌프스입니다. 무채색 드레스와 함께 신으면 신발만 보입니다.",
    story: "패턴이 강해서 옷은 단색으로 가야 합니다. 가방이나 액세서리도 무지로 맞추세요.",
    imageId: "1543163521-1bf539c55dd2",
    imageAlt: "플로럴 프린트 스틸레토 펌프스",
    sizes: HEEL_SIZES,
    moods: ["party", "wedding"],
    isNew: true,
    stock: 4,
  },
  {
    slug: "jimmy-choo-romy-strap",
    name: "Romy Strap Heel",
    nameKo: "로미 스트랩 힐",
    brandSlug: "jimmy-choo",
    category: "luxury",
    shoeType: "heels",
    price: 1120000,
    colorway: "누드 / 블러시",
    materials: "스웨이드, 레더 인솔",
    description: "누드 톤 스웨이드에 가는 스트랩을 올린 힐입니다. 피부색과 이어져 다리 선이 끊기지 않습니다.",
    story: "하객룩 신발을 하나만 고른다면 누드 계열을 권합니다. 어떤 색 드레스와도 맞고 다리도 가장 길어 보입니다.",
    imageId: "1590099033615-be195f8d575c",
    imageAlt: "누드 컬러 스트랩 하이힐 두 켤레",
    sizes: HEEL_SIZES,
    moods: ["wedding", "party", "date"],
    isBestseller: true,
    stock: 7,
  },
  {
    slug: "saint-laurent-lace-bootie",
    name: "Lace-up Ankle Bootie",
    nameKo: "레이스업 앵클 부티",
    brandSlug: "saint-laurent",
    category: "luxury",
    shoeType: "boots",
    price: 1650000,
    colorway: "누드 베이지",
    materials: "스웨이드, 레더 아웃솔",
    description: "발목까지 끈으로 조이는 부티입니다. 끈 간격이 좁아 발목이 가늘어 보입니다.",
    story: "스커트와 신으면 발목에서 시선이 멈춰 다리가 짧아 보일 수 있습니다. 앵클 기장 팬츠와 신는 편이 안전합니다.",
    imageId: "1610398752800-146f269dfcc8",
    imageAlt: "누드 베이지 레이스업 앵클 부티",
    sizes: HEEL_SIZES,
    moods: ["party", "office", "date"],
    stock: 5,
  },
  {
    slug: "balenciaga-heel-ankle-boot",
    name: "Leather Heeled Ankle Boot",
    nameKo: "블랙 레더 힐 앵클 부츠",
    brandSlug: "balenciaga",
    category: "luxury",
    shoeType: "boots",
    price: 1580000,
    colorway: "블랙",
    materials: "폴리시드 카프 레더",
    description: "굽이 있는 짧은 앵클 부츠입니다. 발목에서 딱 끊어지는 기장이라 실루엣이 단정합니다.",
    story: "검정 스키니나 슬랙스와 이어 신으면 다리가 한 줄로 길어 보입니다. 가을·겨울 오피스룩의 정답에 가깝습니다.",
    imageId: "1582897085656-c636d006a246",
    imageAlt: "블랙 레더 힐 앵클 부츠 착용 컷",
    sizes: HEEL_SIZES,
    moods: ["party", "office", "date"],
    stock: 6,
  },
  {
    slug: "bottega-chelsea-boot",
    name: "Leather Chelsea Boot",
    nameKo: "브라운 레더 첼시 부츠",
    brandSlug: "bottega-veneta",
    category: "luxury",
    shoeType: "boots",
    price: 1480000,
    colorway: "코냑 브라운",
    materials: "카프 레더, 엘라스틱 거싯",
    description: "끈 없이 신고 벗는 첼시 부츠입니다. 옆면 밴드가 발등을 잡아줘 헐렁하지 않습니다.",
    story: "출퇴근길에 신고 벗기 편해 실용적입니다. 코냑 브라운은 네이비·그레이·카멜 어디에나 맞습니다.",
    imageId: "1531310197839-ccf54634509e",
    imageAlt: "브라운 레더 첼시 부츠 착용 컷",
    sizes: BOOT_SIZES,
    moods: ["office", "date", "travel"],
    isBestseller: true,
    stock: 9,
  },
  {
    slug: "prada-combat-boot",
    name: "Brushed Leather Combat Boot",
    nameKo: "브러쉬드 레더 컴뱃 부츠",
    brandSlug: "prada",
    category: "luxury",
    shoeType: "boots",
    price: 1750000,
    colorway: "다크 브라운",
    materials: "브러쉬드 레더, 러버 라그솔",
    description: "군화 형태를 다듬어 만든 레이스업 부츠입니다. 밑창이 두껍고 홈이 깊어 눈길이나 비 오는 날에도 미끄러지지 않습니다.",
    story: "무거운 편이라 하루 종일 걷는 날에는 부담스럽습니다. 대신 겨울에 이만큼 든든한 신발이 없습니다.",
    imageId: "1608256246200-53e635b5b65f",
    imageAlt: "다크 브라운 레더 레이스업 컴뱃 부츠",
    sizes: BOOT_SIZES,
    moods: ["travel", "office"],
    stock: 7,
  },
  {
    slug: "gucci-horsebit-loafer",
    name: "Horsebit 1953 Loafer",
    nameKo: "호스빗 1953 로퍼",
    brandSlug: "gucci",
    category: "luxury",
    shoeType: "dress",
    price: 1450000,
    colorway: "라이트 브라운",
    materials: "카프 레더, 골드 호스빗",
    description: "말 재갈 모양의 금속 장식을 얹은 로퍼입니다. 1953년에 처음 나온 이래 형태가 거의 바뀌지 않았습니다.",
    story: "양말을 신을지 말지로 인상이 완전히 달라집니다. 여름엔 덧신, 겨울엔 얇은 니트 삭스를 권합니다.",
    imageId: "1616406432452-07bc5938759d",
    imageAlt: "골드 호스빗 장식이 달린 브라운 레더 로퍼",
    sizes: DRESS_SIZES,
    moods: ["office", "wedding", "date"],
    isBestseller: true,
    stock: 8,
  },
  {
    slug: "berluti-double-monk",
    name: "Double Monk Strap",
    nameKo: "더블 몽크 스트랩",
    brandSlug: "berluti",
    category: "luxury",
    shoeType: "dress",
    price: 2350000,
    colorway: "토바코 브라운 파티나",
    materials: "베네치아 레더, 핸드 파티나",
    description: "끈 대신 버클 두 개로 여미는 구두입니다. 가죽을 손으로 물들여 한 켤레씩 색의 깊이가 다릅니다.",
    story: "이 가격대 구두는 관리가 곧 수명입니다. 신고 나면 슈트리를 넣고, 두세 번 신을 때마다 한 번씩 크림을 먹이세요.",
    imageId: "1533867617858-e7b97e060509",
    imageAlt: "브라운 파티나 더블 몽크 스트랩 구두",
    sizes: DRESS_SIZES,
    moods: ["office", "wedding"],
    stock: 3,
  },
  {
    slug: "celine-platform-sandal",
    name: "Platform Cross Sandal",
    nameKo: "플랫폼 크로스 샌들",
    brandSlug: "celine",
    category: "luxury",
    shoeType: "sandals",
    price: 980000,
    colorway: "버건디 / 내추럴 우드",
    materials: "카프 레더, 우드 플랫폼",
    description: "발등을 가로지르는 넓은 가죽 스트랩과 나무 플랫폼을 결합했습니다. 굽이 있지만 바닥이 평평해 걷기 편합니다.",
    story: "굽 높이에 비해 발이 편한 구조입니다. 여행지에서 오래 걸어야 하는데 샌들을 신고 싶을 때 좋습니다.",
    imageId: "1562273138-f46be4ebdf33",
    imageAlt: "버건디 레더와 우드 플랫폼 크로스 샌들",
    sizes: HEEL_SIZES,
    moods: ["travel", "date", "party"],
    isNew: true,
    stock: 6,
  },

  // ───────────────────── 컨템포러리 · 디자이너 ─────────────────────
  {
    slug: "veja-v10-mint",
    name: "V-10",
    nameKo: "V-10 화이트 민트",
    brandSlug: "veja",
    category: "contemporary",
    shoeType: "sneakers",
    price: 189000,
    colorway: "화이트 / 민트",
    materials: "유기농 코튼, 아마존 천연고무",
    description: "브라질산 천연고무와 유기농 면으로 만든 스니커입니다. 화학 처리를 줄인 대신 소재 특유의 질감이 그대로 남아 있습니다.",
    story: "로고가 작아 조용한 인상을 줍니다. 브랜드를 크게 드러내고 싶지 않을 때 고르는 신발입니다.",
    imageId: "1560769629-975ec94e6a86",
    imageAlt: "화이트와 민트 컬러 레이스가 들어간 미니멀 스니커즈",
    sizes: SNEAKER_SIZES,
    moods: ["walk", "campus", "date", "office"],
    isNew: true,
    stock: 20,
  },
  {
    slug: "churchs-derby-burgundy",
    name: "Leather Derby",
    nameKo: "버건디 레더 더비",
    brandSlug: "churchs",
    category: "contemporary",
    shoeType: "dress",
    price: 890000,
    colorway: "버건디",
    materials: "폴리시드 레더, 굿이어 웰트",
    description: "굿이어 웰트로 제작해 밑창을 여러 번 갈아 신을 수 있습니다. 끈 구멍 부분이 열려 있는 더비라 발등이 높아도 편합니다.",
    story: "검정 구두가 이미 있다면 두 번째는 버건디를 권합니다. 네이비 슈트와 가장 잘 맞습니다.",
    imageId: "1449505278894-297fdb3edbc1",
    imageAlt: "버건디 레더 더비 구두 한 켤레",
    sizes: DRESS_SIZES,
    moods: ["office", "wedding"],
    stock: 10,
  },
  {
    slug: "paul-smith-brogue-teal",
    name: "Suede Brogue",
    nameKo: "틸 스웨이드 브로그",
    brandSlug: "paul-smith",
    category: "contemporary",
    shoeType: "dress",
    price: 620000,
    colorway: "틸 그린",
    materials: "스웨이드, 레더 솔",
    description: "구멍 장식을 넣은 브로그 구두를 청록색 스웨이드로 만들었습니다. 정장 구두의 형태에 색으로 변화를 준 구성입니다.",
    story: "무난한 옷차림에 신발로만 변화를 주고 싶을 때 좋습니다. 스웨이드라 비 오는 날은 피하세요.",
    imageId: "1560343090-f0409e92791a",
    imageAlt: "틸 그린 스웨이드 브로그 구두",
    sizes: DRESS_SIZES,
    moods: ["office", "date", "party"],
    stock: 8,
  },
  {
    slug: "grenson-work-boot",
    name: "Leather Work Boot",
    nameKo: "브라운 워크 부츠",
    brandSlug: "grenson",
    category: "contemporary",
    shoeType: "boots",
    price: 540000,
    colorway: "탄 브라운",
    materials: "오일드 레더, 코만도 솔",
    description: "작업화 형태를 그대로 가져온 레이스업 부츠입니다. 오일을 먹인 가죽이라 신을수록 색이 진해집니다.",
    story: "처음 한 달은 뒤꿈치가 까질 수 있습니다. 두꺼운 양말로 길들이고 나면 오래 신는 신발이 됩니다.",
    imageId: "1520639888713-7851133b1ed0",
    imageAlt: "탄 브라운 레더 워크 부츠 착용 컷",
    sizes: BOOT_SIZES,
    moods: ["travel", "walk"],
    stock: 12,
  },
];

export const PRODUCT_COUNT = PRODUCTS.length;
